sudo:
  false

branches:
  only:
    - master
    - travis-debug

before_install:
  git config user.name "Travis CI"

language:
  node_js
node_js:
  - stable

before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
script:
  - ./test.sh
