sudo:
  false

branches:
  only:
    - master
    - travis-debug

before_install:
  git config user.name "Travis CI"

language:
  node_js
node_js:
  - stable

script:
  ./test.sh
after_script:
  npm run coveralls
